name: lcs
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - matplotlib
  - numpy>=1.6
  - xarray 
  - scipy
  - pandas
  - jupyter
  - jupyterlab
  - pip
  - pyfftw>=0.9.2 
  - Cython>=0.2
  - pip:
    - pyqg