name: lcs
channels:
  - defaults
  - conda-forge
dependencies:
  - python=2.7
  - matplotlib
  - numpy>=1.6
  - xarray 
  - scipy
  - pandas
  - jupyter
  - jupyterlab
  - pip<19.1
  - pyfftw>=0.9.2 
  - Cython>=0.2
  - pip:
    - pyqg
    
