name: lcs-ml
channels:
  - defaults
  - conda-forge
dependencies:
  # these packages are required if you want your environment to show up in jupyterlab
  - python=3.8 # has to be <=3.8 for tensorflow to install
  - ipywidgets
  # commonly used packages  
  - xarray 
  - numpy
  - scipy
  - dask
  - pandas
  - zarr
  # data visualization
  - matplotlib
  - cartopy
  # project specific packages
  - pyfftw
  - Cython
  # machine learning packages
  - tensorflow

    

