name: pyqg_run
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - matplotlib
  - numpy
  - xarray 
  - scipy
  - pandas
  - jupyter
  - jupyterlab
  - pip
  - pyfftw
  - Cython
  - pip:
    - pyqg
    
